apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: surajrl/cart-service:<VERSION>
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          # TODO: Move env variables to a Secret and ConfigMap object
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_HOST
              value: "cart-db-svc"
            - name: MYSQL_PORT
              value: "3307"
            - name: MYSQL_DATABASE
              value: "cart-db"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-svc
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - port: 8002
      targetPort: 8002
