apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cloud-native-web-app-ip
spec:
  defaultBackend:
    service:
      name: frontend-svc
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector: # Select Pods to forward the requests to
    app: frontend
  ports:
    - port: 80 # Expose 'port'
      targetPort: 3000 # Forward traffic coming to 'port' to 'targetPort'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1 # How many Pods to create
  selector:
    matchLabels: # All the pods that match this label will belong this Deployment
      app: frontend
  template: # Configuration for the Pod
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: surajrl/frontend:<VERSION>
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Port where the container will listen
