apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: item-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
---
apiVersion: v1
kind: Service
metadata:
  name: item-db-svc
spec:
  type: ClusterIP
  selector:
    app: item-db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-db-deployment
  labels:
    app: item-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-db
  template:
    metadata:
      labels:
        app: item-db
    spec:
      containers:
        - name: item-db
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: item-db-persistent-storage
              mountPath: /data/db
      volumes:
        - name: item-db-persistent-storage
          persistentVolumeClaim:
            claimName: item-db-pvc
