apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: message-service-health-check
spec:
  healthCheck:
    checkIntervalSec: 30 # Interval between health checks
    timeoutSec: 5 # Timeout for each health check
    healthyThreshold: 2 # Number of successful checks to mark as healthy
    unhealthyThreshold: 2 # Number of failed checks to mark as unhealthy
    type: HTTP # Health check type (HTTP, HTTPS, or TCP)
    requestPath: /message/health # Path to be checked
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message-service-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: message-service-ip
    cloud.google.com/backend-config: '{"default": "message-service-health-check"}'
spec:
  defaultBackend:
    service:
      name: message-service-svc
      port:
        number: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: message-service-svc
spec:
  type: NodePort
  selector:
    app: message-service
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-deployment
  labels:
    app: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: surajrl/message-service:<VERSION>
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          # TODO: Move env variables to a Secret and ConfigMap object
          env:
            - name: MONGO_URL
              value: "mongodb+srv://nbhandari1:Hello@chat.lrbggsa.mongodb.net/production?retryWrites=true&w=majority"
