CREATE DATABASE IF NOT EXISTS `cart-db`;
USE `cart-db`;
DROP TABLE IF EXISTS `cart`;
DROP TABLE IF EXISTS `cart_item`;
CREATE TABLE cart (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL
);
CREATE TABLE cart_item (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cart_id INT NOT NULL,
  item_id VARCHAR(255) NOT NULL,
  FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE
);